export const FORM_SECTIONS = [
  {
    id: 'profile',
    title: 'Your Profile',
    emoji: '👤',
    description: 'Basic info to personalise your results',
    fields: [
      {
        name: 'Age',
        label: 'Age',
        type: 'slider',
        min: 13, max: 35, step: 1,
        unit: 'yrs',
        hint: 'Your current age',
      },
      {
        name: 'Gender',
        label: 'Gender',
        type: 'select',
        hint: 'Select your gender',
        options: [
          { value: 'Male', label: 'Male' },
          { value: 'Female', label: 'Female' },
          { value: 'Non-binary', label: 'Non-binary' },
          { value: 'Prefer not to say', label: 'Prefer not to say' },
        ],
      },
      {
        name: 'Student_Working_Status',
        label: 'Current Status',
        type: 'select',
        hint: 'What best describes you right now?',
        options: [
          { value: 'Student', label: 'Student' },
          { value: 'Working', label: 'Working' },
          { value: 'Both', label: 'Both (Student + Working)' },
          { value: 'Neither', label: 'Neither' },
        ],
      },
      {
        name: 'Country',
        label: 'Country',
        type: 'select',
        hint: 'Where are you based?',
        options: [
          { value: 'India', label: 'India' },
          { value: 'USA', label: 'USA' },
          { value: 'UK', label: 'UK' },
          { value: 'Canada', label: 'Canada' },
          { value: 'Australia', label: 'Australia' },
          { value: 'Other', label: 'Other' },
        ],
      },
      {
        name: 'Content_Type_Preference',
        label: 'Favourite Content Type',
        type: 'select',
        hint: 'What do you consume most online?',
        options: [
          { value: 'Short videos', label: 'Short videos (Reels/TikTok)' },
          { value: 'Long videos', label: 'Long videos (YouTube)' },
          { value: 'News', label: 'News & Articles' },
          { value: 'Gaming', label: 'Gaming content' },
          { value: 'Social posts', label: 'Social posts & memes' },
          { value: 'Educational', label: 'Educational content' },
        ],
      },
    ],
  },
  {
    id: 'digital',
    title: 'Digital Habits',
    emoji: '📱',
    description: 'How you spend your time online each day',
    fields: [
      {
        name: 'Daily_Social_Media_Hours',
        label: 'Daily Social Media Hours',
        type: 'slider',
        min: 0, max: 12, step: 0.5,
        unit: 'hrs/day',
        hint: 'Instagram, TikTok, Twitter, etc.',
      },
      {
        name: 'Screen_Time_Hours',
        label: 'Total Screen Time',
        type: 'slider',
        min: 0, max: 18, step: 0.5,
        unit: 'hrs/day',
        hint: 'All devices combined',
      },
      {
        name: 'Online_Gaming_Hours',
        label: 'Online Gaming Hours',
        type: 'slider',
        min: 0, max: 12, step: 0.5,
        unit: 'hrs/day',
        hint: 'Any online games or esports',
      },
      {
        name: 'Night_Scrolling_Frequency',
        label: 'Night Scrolling Frequency',
        type: 'slider',
        min: 0, max: 7, step: 1,
        unit: 'nights/week',
        hint: 'How many nights/week do you scroll in bed before sleep?',
      },
    ],
  },
  {
    id: 'sleep',
    title: 'Sleep & Lifestyle',
    emoji: '😴',
    description: 'Your rest and physical activity patterns',
    fields: [
      {
        name: 'Daily_Sleep_Hours',
        label: 'Daily Sleep Hours',
        type: 'slider',
        min: 2, max: 12, step: 0.5,
        unit: 'hrs/night',
        hint: 'Average over the past week',
      },
      {
        name: 'Sleep_Quality_Score',
        label: 'Sleep Quality',
        type: 'rating',
        min: 1, max: 10,
        unit: '/10',
        hint: '1 = very poor sleep, 10 = excellent sleep',
      },
      {
        name: 'Exercise_Frequency_per_Week',
        label: 'Exercise Frequency',
        type: 'slider',
        min: 0, max: 7, step: 1,
        unit: 'days/week',
        hint: 'Any physical activity (gym, walk, sport)',
      },
      {
        name: 'Caffeine_Intake_Cups',
        label: 'Caffeine Intake',
        type: 'slider',
        min: 0, max: 10, step: 1,
        unit: 'cups/day',
        hint: 'Coffee, energy drinks, tea combined',
      },
      {
        name: 'Study_Work_Hours_per_Day',
        label: 'Study / Work Hours',
        type: 'slider',
        min: 0, max: 16, step: 0.5,
        unit: 'hrs/day',
        hint: 'Active studying or working hours',
      },
    ],
  },
  {
    id: 'mental',
    title: 'Mental State',
    emoji: '🧠',
    description: 'How you have been feeling lately',
    fields: [
      {
        name: 'Anxiety_Score',
        label: 'Anxiety Level',
        type: 'rating',
        min: 1, max: 10,
        unit: '/10',
        hint: '1 = very calm, 10 = very anxious',
      },
      {
        name: 'Overthinking_Score',
        label: 'Overthinking',
        type: 'rating',
        min: 1, max: 10,
        unit: '/10',
        hint: '1 = rarely overthink, 10 = constantly overthinking',
      },
      {
        name: 'Mood_Stability_Score',
        label: 'Mood Stability',
        type: 'rating',
        min: 1, max: 10,
        unit: '/10',
        hint: '1 = very unstable, 10 = very stable',
      },
      {
        name: 'Motivation_Level',
        label: 'Motivation Level',
        type: 'rating',
        min: 1, max: 10,
        unit: '/10',
        hint: '1 = no motivation, 10 = highly motivated',
      },
      {
        name: 'Emotional_Fatigue_Score',
        label: 'Emotional Fatigue',
        type: 'rating',
        min: 1, max: 10,
        unit: '/10',
        hint: '1 = feeling fresh, 10 = completely drained',
      },
      {
        name: 'Social_Comparison_Index',
        label: 'Social Comparison',
        type: 'rating',
        min: 1, max: 10,
        unit: '/10',
        hint: '1 = never compare myself, 10 = constantly comparing',
      },
    ],
  },
]

export const DEFAULT_VALUES = {
  Age: 21,
  Gender: 'Male',
  Country: 'India',
  Student_Working_Status: 'Student',
  Content_Type_Preference: 'Short videos',
  Daily_Social_Media_Hours: 3,
  Screen_Time_Hours: 6,
  Online_Gaming_Hours: 1,
  Night_Scrolling_Frequency: 3,
  Daily_Sleep_Hours: 7,
  Sleep_Quality_Score: 5,
  Exercise_Frequency_per_Week: 3,
  Caffeine_Intake_Cups: 2,
  Study_Work_Hours_per_Day: 6,
  Anxiety_Score: 5,
  Overthinking_Score: 5,
  Mood_Stability_Score: 5,
  Motivation_Level: 5,
  Emotional_Fatigue_Score: 5,
  Social_Comparison_Index: 5,
}
